version: '3.8'
services:
  mongo1:
    image: mongo:4.4
    container_name: mongo1
    networks:
      - mongo-cluster
    environment:
      - MONGO_INITDB_REPLICA_SET=rs0
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo1_data:/data/db

  mongo2:
    image: mongo:4.4
    container_name: mongo2
    networks:
      - mongo-cluster
    environment:
      - MONGO_INITDB_REPLICA_SET=rs0
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo2_data:/data/db

  mongo3:
    image: mongo:4.4
    container_name: mongo3
    networks:
      - mongo-cluster
    environment:
      - MONGO_INITDB_REPLICA_SET=rs0
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo3_data:/data/db

  mongo_setup:
    image: mongo:4.4
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo-cluster
    command: >
      bash -c "
        sleep 10;
        echo 'Configuring replica set';
        mongo --host mongo1:27017 <<EOF
        rs.initiate({
          _id: 'rs0',
          members: [
            { _id: 0, host: 'mongo1:27017' },
            { _id: 1, host: 'mongo2:27017' },
            { _id: 2, host: 'mongo3:27017' }
          ]
        });
      "

networks:
  mongo-cluster:
    driver: bridge

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
